FROM openjdk:11-jre-slim-buster

ENV app_name thunder

RUN apt-get update
RUN apt-get install -y curl net-tools

RUN mkdir -p /opt/$app_name/
RUN mkdir -p /var/log/$app_name/


COPY ./output/*.jar /opt/$app_name/$app_name.jar
RUN ls /opt/$app_name/