server:
  port: 8080
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /application
  metrics:
    web:
      server:
        request:
          autotime:
            percentiles: 0.95,0.90,0.99