spring.jackson.serialization.FAIL_ON_EMPTY_BEANS: false
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pearl?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# MyBatis
# mapper.xml 위치 지정
mybatis:
  mapper-locations: classpath:mapper/*.xml